# Generated by Django 3.2.4 on 2021-06-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_type_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('Drinks', 'نوشیدنی ها'), ('Breakfast', 'صبحانه'), ('Dinner', 'شام ')], default='Lunch', max_length=10, verbose_name='نوع غدا'),
        ),
    ]
