# Generated by Django 3.2.4 on 2021-06-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_food_type_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('drinks', 'نوشیدنی ها'), ('breakfast', 'صبحانه'), ('dinner', 'شام'), ('lunch', 'ناهار')], default='dinner', max_length=10, verbose_name='نوع غدا'),
        ),
    ]
