# Generated by Django 3.2.4 on 2021-06-25 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_food_type_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='pub_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتظار'),
        ),
    ]
