# Generated by Django 3.2.4 on 2021-07-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_alter_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('drinks', 'نوشیدنی ها'), ('breakfast', 'صبحانه'), ('dinner', 'شام')], default='dinner', max_length=10, verbose_name='نوع غدا'),
        ),
    ]
