# Generated by Django 3.2.4 on 2021-07-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='pub_time',
        ),
    ]
