# Generated by Django 3.2.4 on 2021-07-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210724_0315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='blog',
            new_name='comments',
        ),
    ]
