# Generated by Django 3.2.4 on 2021-07-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_comments_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='blogs', to='blog.Tag', verbose_name='تگ ها'),
        ),
    ]
