# Generated by Django 3.2.4 on 2021-07-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_comments_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='عنوان لاتین'),
        ),
    ]
