# Generated by Django 3.2.4 on 2021-07-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_comments_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='slug',
        ),
    ]
