# Generated by Django 3.2.4 on 2021-07-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.IntegerField(max_length=12, verbose_name='تلفن'),
        ),
    ]
